name: Build and Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm install -g http-server

    - name: Build and test
      run: |
        npm run build
        http-server ./dist -p 8080 &
        sleep 3
        curl -I http://localhost:8080/index.html

    - name: Lint and test CSS
      run: |
        npm run lint:css
        npm run test:css

    - name: Lint and test JS
      run: |
        npm run lint:js
        npm run test:js
